spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/Documents/h2/testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    password: sa
    username: password
    initialization-mode: never

    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 30000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000

      validation-query: select '1'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20

      filters: stat,wall
      aop-patterns: com.springboot.servie.*

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: druid
        login-password: druid

      filter:
        stat:
          log-slow-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    locations: classpath:db/migration/postgres

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  devtools:
    restart:
      exclude: static/**, public/**

  # h2
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  main:
    lazy-initialization: true

server:
  port: ${PORT:8080}

# metric
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

# sql log level
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          EnumType: TRACE
          descriptor:
            sql:
              BasicBinder: TRACE
    org.springframework.data.mongodb.core: debug

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

graphql:
  servlet:
    websocket:
      enabled: false